---
title: "Summarising data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
library(ggvis)

mtcars

plot(mtcars$mpg, mtcars$wt)

mtcars
attach(mtcars)
plot(mpg, wt)

mtcars %>% ggvis( ~mpg, ~wt) %>% layer_points()
mtcars %>% ggvis( ~mpg, ~wt) %>% layer_lines()
mtcars %>% ggvis( ~mpg, ~wt) %>% layer_bars()
mtcars %>% ggvis( ~mpg, ~wt) %>% layer_smooths()

#????????? ?????? ????????????
mtcars %>% ggvis( ~mpg, ~wt) %>% layer_points() %>% layer_smooths()

mtcars %>% ggvis( ~mpg, ~wt, fill:="red") %>% layer_points() %>% layer_smooths()

mtcars %>% ggvis( ~mpg, ~wt, fill="cyl") %>% layer_points() %>% layer_smooths()

mtcars %>% ggvis( ~mpg, ~wt, fill= ~cyl) %>% layer_points() %>% layer_smooths()
#???????????? continuous??? ???????????? ????????? ????????? ??????
str(mtcars)
#cyl=num ???????????? ????????? ??????

mtcars$cyl <- factor(mtcars$cyl)
str(mtcars)

mtcars %>% ggvis( ~mpg, ~wt, fill= ~cyl) %>% 
            layer_points() %>% layer_smooths() %>%
            add_axis("x", title = "MPG", values = c(0:35))

mtcars %>% ggvis( ~mpg, ~wt, fill= ~cyl) %>% 
  layer_points() %>% layer_smooths() %>%
  add_axis("x", title = "MPG", values = c(10:35)) %>%
  add_axis("y", title = "WT", subdivide = 4)


```

